version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5001:5000" 
    volumes:
      - ${DATASET_PATH}:/app
    environment:
      - FLASK_ENV=development
    container_name: flask-app