version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"  
      - "23000:23000/udp"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./storage:/app/storage  
      - ./app.py:/app/app.py  
    networks:
      - udp_network

networks:
  udp_network:
    driver: bridge